### ISSUE TITLE
BUG: Won't Export App

### ISSUE THREAD

**Issue by everythingability** [benjie-git/CardStock#17]
Hi,

amazed that this exists. Great job! Loving it.

When I export my app on Sonoma 14.5, CardStock 099.6.2 , I get an app but when I launch it nothing happens. There's no clue in the System Preferences window.

Tom

**Comment by benjie-git** [comment]
Hmmm, this works fine for me on MacOS 14.7 on Arm.  I'll test more with the downloaded versions.  Are you running on an Intel or Arm machine?  And are you running the Intel or Arm download?

**Comment by everythingability** [comment]
M2 Arm. And the ARM download (I hope/reckon)

<img width="604" alt="image" src="https://github.com/user-attachments/assets/67e5d8b0-0489-4fa6-a292-3d0c3cbab5e3">

**Comment by benjie-git** [comment]
This works fine if running from source, but PyInstaller fails to include the requests package inside the standalone app, for requests>=2.32.0.  This works with requests<=2.31.0.  Fixed in git, so the next builds will include this fix.

**Comment by benjie-git** [comment]
I posted a pre-release v0.99.7_pre1 version with pre-built arm mac app that
should fix this issue.  Please let me know if it works for you!

**Comment by everythingability** [comment]
<img width="603" alt="image" src="https://github.com/user-attachments/assets/cc78ef3a-e33d-4413-9ddb-d4bec3a778e1">

It DOES successfully export now... Yay! There is a slight UI issue that, having exported an app, the window kinda just lurks there... looking as if it's still in progress, or failed... when it should close - make a ping or something ...or reveal it in the Finder... 

Still. Great . Thanks.

**Comment by benjie-git** [comment]
The export window does automatically close for me when the export is complete.  Are you able to run the app from the terminal and see if there are any error messages?  You should be able to run in the terminal from the directory containing the CardStock.app as `CardStock.app/Contents/MacOS/CardStock`

**Comment by everythingability** [comment]
Ak. OK. I tried and the first time it complained about an image... not sure what to do about that. The image is where it says it is.

The 2nd time it complained because the file/Stack already exists.

tas509@UOY24M162 ~ % /Applications/CardStock.app/Contents/MacOS/CardStock 
Traceback (most recent call last):
  File "stackExporter.py", line 493, in OnExportApp
  File "stackExporter.py", line 170, in ExportApp
  File "stackExporter.py", line 313, in ExportFromBundle
  File "shutil.py", line 260, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tas509/Desktop/GZoZe6aWgAoAsM3.jpg'
Traceback (most recent call last):
  File "stackExporter.py", line 493, in OnExportApp
  File "stackExporter.py", line 170, in ExportApp
  File "stackExporter.py", line 280, in ExportFromBundle
  File "shutil.py", line 600, in copytree
  File "shutil.py", line 498, in _copytree
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/Users/tas509/Desktop/MyStack.app'

**Comment by everythingability** [comment]
Just tried **Remove** for the image - btw this dialog wasn't clear as to what it was telling me and what to do about it... and it fixed it.

Super!

**Comment by benjie-git** [comment]
The app will now show error messages during export, and close the export dialog cleanly after an error.  I still need to determine why it couldn't find your image.

**Comment by everythingability** [comment]
The dialog wasn't clear as to what I should do with the image... SHOULD I
add it or remove it?  I think each time I tried to build I just ignored
that message.

I can't remember, I might have removed the image from the stack so thought
it should be ignored... Maybe I'd deleted/renamed the image.

**Comment by benjie-git** [comment]
I'll try to make this dialog more clear.  The idea is that it's packaging up all of your resources into the exported stack, and is confirming that it found everything your stack will need, in terms of sounds and images.  If you delete them from this list, it will not include them in the packaged stack app.  It may still find them at run time, if you run the exported stack from the same location as your original stack, since the relative paths to the images/sounds will still be in the same relative locations.

But it does sound like the export tool is having trouble finding your images that are in the Desktop folder.  I'll see if I can figure out why that could be happening.

**Comment by everythingability** [comment]
Hi,

I think stating what the issue is (if there an is an issue). For example, if an image is missing, does Cardstock crash, or is the image just missing?  

I honestly can't remember if I'd added an image that was lying around that I later tidied up.
